spring:
  application:
    name: hcms-api-gateway
server:
  port: 8888
zuul:
  routes: 
   diagnostic-user-management:
      path: /admin/**
      service-id: hcms-user-management-system
      strip-prefix: false
      
   diagnostic-user:
      path: /user/**
      service-id: hcms-user-management-system
      strip-prefix: false 
     
   diagnostic-center-management:
       path: /center/**
       service-id: hcms-diagnostic-center-management-system
       strip-prefix: false
       
   diagnostic-test-management:
       path: /test/**
       service-id: hcms-diagnostic-test-management-system
       strip-prefix: false
    
   diagnostic-application-management:
      path: /appointmentadmin/**
      service-id: hcms-appointment-management-system
      strip-prefix: false   

   application-management:
      path: /appointmentuser/**
      service-id: hcms-appointment-management-system
      strip-prefix: false   

    